human_backgrounds = {

"A Pirates Life for Thee" : "You sailed the Seven Seas aboard a pirate ship! Start with a cutlass and a pirate accent. Choose: a peg-leg, a hook-hand, or eye-patch.", 
"Academician" : "You were fortunate enough to get a good education. You speak multiple languages but can’t swim. Start with a staff and a bag containing 1d4 academic books.", 
"Accused of Witchcraft" : "You were accused of being a witch! The au- dacity! You were nearly burned alive but were able to use your witchcraft to escape. Gain +1 to tests related to casting spells. Start with a random spell scroll, a wand, and a black cat familiar.", 
"Acolyte" : "You were taken to the tem- ple as a young child and raised as an acolyte of Solarion. You’ve been sent to work on behalf of your temple. Start with holy robes, a wooden holy symbol, and a staff.", 
"Amnesia" : "You have no idea who you are or where you came from. You woke up in the gutter one night and have been begging to get by until now. Gain amnesia.", 
"Animal Trainer" : "You grew up train- ing animals. Start with a pet of your choice (cat, dog, pidgeon, rat, etc), a club, and a net.", 
"Ape Man" : "You were lost in the jungle as a child but were taken in by a group of gorillas. You can climb trees like an ape but speak in only grunts, hoots, and howls. Start with a club and a cheetah-skin loincloth.", 
"Apprentice Alchemist" : "Your men- tor died in an explosive alchemy accident. Start with a dagger, a vial of quicksilver, and a ring made of a metal no one can identify.", 
"Apprentice Astronomer" : "Your father taught you how to peer into the heavens. Start with a dagger, an astrolabe, and an armillary sphere.", 
"Artisan" : "You were a skilled artisan and member of a guild. Monot- ony bored you. You can reliably perform your craft (1d10: 1 potter, 2 glassblower, 3 mason, 4 jeweler, 5 haberdasher, 6 tinker, 7 vintner, 8 cobbler, 9 weaver, 10 chef). Start with appropriate tools and 1d6x10cp worth of trade goods for your profes- sion, plus a club.", 
"Assassin in Training" : "You’ve been sent by your clan to hone your skills on the frontier. Start with a vial of poison, a dagger, and a hooded cloak.", 
"Avenger" : "Life was simple back home. Then the monsters came and killed your family. Now you’re out for revenge. Start with an axe, a ha- tred for monsters, and an old music box that plays a song you used to know the words to.", 
"Axe-for-hire" : "There aren’t many problems that can’t be solved by a well-placed axe. It’s been your living thus far. Start with an axe and spiked boots.", 
"Barefoot Friar" : "In the name of your god Solarion, you’ve eschewed footwear as a sacrifice. Start with a mace and a holy symbol. You can walk barefoot as if you were wearing boots.", 
"Blade in the Boulder" : "You were a young villager who attempted to pull an old sword stuck in a boulder. To everyone’s surprise, it worked. Rumors abound about you. The legend says you’re to rule the land one day. Start with a +1 sword called Excelsus and a sense of destiny.", 
"Bounty Hunter" : "You earned your keep by pursuing criminals and wanted targets across borders. Start with a club, a net, and a wanted poster.", 
"Bowyer-Fletcher" : "Earned your keep as a bowyer-fletcher, crafting bow and arrow alike. Gain the bow- yer-fletcher skill, a short bow, and a quiver full of arrows.", 
"Brewer" : "Your family were brewers but the family business failed when a rival poisoned your stock. Start with a club and a jug of ale.", 
"Brute" : "A member of the brute squad, tasked with keeping the peace when crowds become rowdy and violent. You’re a huge person, able to throw around weight and muscle. If it’s not already, set your Strength to +3. Start empty-handed.", 
"Cavalry" : "Were part of the caval- ry before the unit dissolved. Your warhorse was taken from you, but you managed to commandeer a pony. Start with a pony and a mace.", 
"Circus Folk" : "You were a member of a circus troupe. You left due to mis- treatment and underpayment. Start with a dagger, a 10-foot pole, chalk, and performance garb.", 
"Courtesan" : "That work is behind you now. Start with a dagger, a red cloak, and a brand on your neck.", 
"Courtier" : "You were a wealthy dilet- tante attending noble gatherings. A dark time fell upon your family and you were stripped of titles. Start with a short sword and fancy clothing.", 
"Cutpurse" : "You got by with your skill in picking pockets and lifting valuables from the unaware. Start with a sap, a coat lined with secret pockets, and a strange coin stolen from a friend.", 
"Delusional Knight" : "You’re not really a knight. You had a very vivid fever dream once wherein you were knighted by a queen and believe wholeheartedly, to this day, that it actually happened. You’ve spent your life since upholding the laws of chivalry, to the best of your limited knowledge. Start with “pots and pans armor” (equivalent to hide armor but also loud), a shield, a short sword, and an old scrawny horse.", 
"Demon Cultist" : "You secretly wor- ship a demon (1d6: 1 Xoa’phont, 2 Zetherain, 3 Baruun'rath 4 Ashaar Kai, 5 Sheeokk, 6 Var'zuuth) and are part of a cult who seeks to discreetly thwart rival cults of other demons. Start with a crooked dagger and an idol to your demon god.", 
"Discovered Power" : "You one day stumbled across a magical orb and have dedicated your life to learning how to harness its power. Start with a crystal ball, a dagger, and a book of arcane lore.", 
"Dishonored" : "Child of a noble-house but an altercation lead to your banishment. You now seek to restore your name or otherwise grasp at some sort of power. Start with a sword, fine clothing, 1d6x10 silver pieces, a notable surname, and ruth- less ambition.", 
"Escaped from a Witch" : "You were a pet and slave to a mad witch up until a few days ago when you escaped. You’re immune to charm magic but have haunting dreams and seething paranoia. Start with a dagger, a small cloth with the invisibility spell writ- ten on it in blood, and a sorrowful torture scar.", 
"Escaped from Cult" : "You were a in cult that worshiped chaos gods. They decided to sacrifice you as an offering, but you managed to escape. Their assassins will find you one day. Gain a dagger, a hooded cloak, and a forbidden tattoo on your forehead.", 
"Escaped from Prison" : "You never want to go back there. Start with a club, a set of manacles, and some scary-looking tattoos.", 
"Estranged" : "You have a spouse and 2d4 children back home that you must occasionally send some money to. Failure to do so and you’ll gain a hefty bounty on your head. Start with a spear and the deed for a piece of property in a far off place.", 
"Executioner" : "You claimed the lives of many criminals who put their neck on the chopping block. Start with a black hood and a battle axe.", 
"Exercised" : "You experienced demon- ic possession and had to be exercised by a holy priest. It didn’t fully work and the demon now hides in the back of your mind, occasionally whisper- ing suggestions. Start with a dagger and a voice in your head.", 
"Failed Merchant" : "Business tanked one too many times. Start with a dagger, a cart containing 200cp in commodities, and 500cp in debt.", 
"Falconer" : "You lost your position within the guild. Now you’re on the frontier to find work and seek out rare birds. Start with a sling, a leath- er gauntlet, and a trained falcon.", 
"Far-Traveled" : "Your parents were traveling merchants who specialized in transporting goods across borders. You traveled with them. You can speak two other languages of your choice. Start with a rapier and a jour- nal written in a foreign language.", 
"Fence" : "Worked for a thief’s guild, buying and selling stolen items from local crooks. Start with a dagger and a gold ring.", 
"Fisher-folk" : "You were raised as a spear fisher. You can hold your breath thrice as long as others. Start with a net, a javelin, fishing gear, and a strange figurine carved from coral.", 
"Footpad" : "You ransacked and robbed unsuspecting caravans who passed too close to your territory. Start with a short sword and a sling.", 
"Fortune Teller" : "You were a member of a traveling circus, telling fortunes for coins. Your act was mostly a sham, but sometimes you’d surprise yourself. Can convincingly feign the augury spell, but there is 1-in-6 chance it actually works (Intellect check). Start with a dagger, a deck of tarot cards, and a glass ball. One of the tarot cards looks like someone in your party.", 
"Fugitive" : "You murdered someone and are now on the run. Start with a dagger, false travel papers, and a bounty on your head.", 
"Gambler" : "You’re a gambler on the run from gambling debts. Start with a bottle of expensive or rare wine you won in a card game.", 
"Gladiator" : "You killed for throngs of wailing onlookers but managed to escape. Start with a javelin, a net, and a helmet.", 
"Gravedigger" : "You buried the dead and kept the cemetery free of rob- bers. Start with a club, a shovel, and a bag.", 
"Grievanced Farmer" : "You toiled in the fields and tilled the land but your acreage was seized by local nobles. Start with a club, a bag of turnips, and a seething hatred for nobles.", 
"Grifter" : "You were a successful con-artist, grifting gullible marks left and right. Winds took a sour turn and you had to skip town. Start with a dagger, a bag of fake jewels, and a forgery kit.", 
"Guard at a Noble House" : "Accused of stealing and banished. Start with a padded armor, a spear, and a piece of jewelry worth 1gp.", 
"Healer" : "You know the ways of heal- ing the sick and wounded. Start with a dagger, a healing kit, and a needle that never seems to dull.", 
"Hedge Mage" : "You practiced home- made magic in your yard. The constabulary would have nothing of it and ran you out of town. Start with a staff, a scroll of control plants, and your father’s smoking pipe (smoke exhaled from it forms into moving likeness of your thoughts).", 
"Hermit" : "You hid away, studying an- cient tomes of knowledge in solitude. But your studies can only bring your knowledge so far. Start with a staff, a bag with 1d4 historic or religious books, and an idol carved from jade that seems to whisper to you at night. You worship the goddess Lunara.", 
"Highlander" : "You are a kilted warrior from the highland clans, seeking to prove their mettle in combat against worthy foes. Inflict a critical hit on natural 19-20. Start with a sword, a kilt, and a set of bagpipes.", 
"Hound Master" : "You trained the dogs and maintained the kennels for a noble house but were terminated from service due to a personality clash. Start with a guard hound and a club.", 
"Ice Age Hunter" : "You were a hunt- er-gatherer born 10,000 years ago during a great ice age. An avalanche entombed you in ice. Some workers dug you up on accident a few days ago and you miraculously regained consciousness. After wandering aimlessly, you fell in with some adventurers who just think you’re a wildling. Gain a +1 to Strength, Agil- ity, and Perception, but -1 to Intellect and Charisma. You speak in a grunt- based language. Start with a club and loincloths made from saber-tooth tiger pelts.", 
"Imposter" : "You aren’t who you say you are. Roll again to determine the background you pretend to be, and then a third time to determine your actual background. Start with the items of your fake background and any special features of your real background.", 
"Intrepid" : "You happened across a treasure map and couldn’t pass up the opportunity. Start with an old treasure map, a strangely-etched dou- bloon, a short sword, and a compass.", 
"Kidnapped Blacksmith" : "You spent your youth learning to forge metals but wild circumstances lead to your capture by pirates. Start with a hammer, a cutlass, and a jolly roger stained with your blood.", 
"Lore Keeper" : "You were a lore keep- er, hoarding books and knowledge in order to keep it out of the wrong hands. You’ve been sent to collect lost knowledge. Start with a staff and a bag of books.", 
"Mercenary" : "You were discharged without pay and have come to the frontier to find work. Start with a sword and an obvious brand that marks you as a mercenary.", 
"Merry Marksman" : "You were a tal- ented and noble bowman, but seeing the people oppressed by a corrupt ruler turned you to a life of highway robbery, where you stole from the rich to give to the poor. Start with a green tunic, a feathered cap, and a longbow with a quiver of arrows.", 
"Militia Deserter" : "A member of a civil militia who deserted during a harsh winter. You have been on the run since. Start with a javelin and padded armor.", 
"Miner" : "You toiled in the mines. Start with a pickaxe, a lantern, a block of strange stone that is lighter and harder than expected, and a nagging cough.", 
"Monk" : "You stumbled upon lost holy scriptures of Solarion hidden in a cave and spent years studying them. Start with a staff and an ancient holy book with some important pages missing.", 
"Moon Sage" : "You are a sage who found a lost tome of the goddess Lunara in some caves near the sea. You’ve studied her teachings since. Start with a staff, a lens, and a stone disk carved to look like the moon.", 
"Mountaineer" : "Your family lived off the land in a remote mountain forest, surviving for generations. Start with a green cloak and a short bow with quiver of arrows.", 
"Night Watchman" : "A night watch- man for a city down south. Guilty or not, your unit was dishonorably dis- missed for corruption. Gain a helmet, a lantern, and a spear.", 
"Northern Wildling" : "You come from the savage north to crush your enemies, see them driven before you, and hear the lamentations of their harem. You’re ambitious, uncouth, and hot-headed. +1 to damage rolls. Start with an axe and a fur cloak.", 
"Orphan" : "You were orphaned as a young child and grew up with a rough life as a beggar. You fled the city because some thugs wanted you dead. Start with a dagger, a necklace with a locket you can’t get open, and enemies still looking for you.", 
"Outcast Heir" : "You are the heir to a noble crown, but you’ve gone into hiding because your tyrant of an uncle has sent assassins to kill you. Start with an ancestral sword, a fur- lined cloak, and brooding personality.", 
"Outlaw" : "You’ve got a notorious reputation. You’re on the run from bounty hunters. Start with a short sword, a black cloak, and a bounty on your head.", 
"Outrider" : "You were tasked with patrolling the valleys and fields upon your trusty steed. Your band was routed and you lost your mare, but you’ve sourced another mount since. Start with a spear, a pony, and a sil- ver octopus pendant that glows when water is near.", 
"Pathfinder" : "You specialized in guid- ing caravans through the wilderness. Start with an axe, a compass, and a sliver of stone that always seems warm - it sparks when you strike it against something hard.", 
"Pilgrim" : "A pilgrim who’s traveled to the frontier in search of lost holy sites to anoint and rebuild. Gain a staff, the religion skill, and a book of holy songs to Solarion. A small, stone statue of a forgotten saint.", 
"Poison Taster" : "You were tasked with tasting a noble’s meal in case of poison. You indeed ate some and were left for dead, but recovered. You’re immune to poison but can’t taste anything. Start with a dagger and an antidote.", 
"Questing Squire" : "You are a young knight-in-training, sent by your mas- ters to prove yourself. Start with a sword, a shield, and a suit of padded armor.", 
"Rat Catcher" : "You were a ratter but you lost your job. Start with a club, a net, a grotesque trophy of the biggest rat you’ve bashed, and a bag of rare shells and other hard animal parts.", 
"Reborn" : "You died and were resurrected by a demon who now owns your soul. It whispers to you occasionally and haunts your dreams. Start with a hooded cloak, a dagger, and a nasty scar.", 
"Reeve" : "You were a shire reeve, tasked with upholding the law and overseeing tax. Your status was re- voked after the king discovered foul play. Start with a sword, fine garb, a royal stamp, and a an old decree signed by the king.", 
"Runaway Princess" : "They wanted you to stay couped up. You showed them. Besides, you can handle yourself. Start with a rapier, fancy clothes, and golden circlet with an inlaid gem (worth 2d6gp).", 
"Sailor" : "You sailed the Seven Seas aboard a mighty galleon. Start with a cutlass, a coast map, and a compass.", 
"Saw the Light" : "You went on a spir- itual journey and the saw the light of Solarion. Start with robes, a staff, and a holy book. Choose a deity to worship.", 
"Scullery Maid" : "For years you worked for a noble house, scrubbing dirty pots and pans, and cleaning up after the spoiled masters. You’ll have no more of that. Start with a dagger, a bag of soap, and stolen piece of jewelry worth 1d4 gold.", 
"Shepherd" : "You tended to a flock of sheep but they were hunted to death by a pack of wolves. Start with a staff and one last sheep.", 
"Smuggler" : "You transported contra- band across borders, but you were caught and your ship was confiscat- ed. You managed to escape and fled to the frontier. Start with a sling and a false-bottom backpack.", 
"Spy" : "You were a professional spy. Things got complicated and you had no choice but to disappear and start anew. Start with a dagger and a dis- guise kit. You can convincingly fake accents and alternate voices.", 
"Student Wizard" : "Attended a hidden preparatory school for young wiz- ards. Have a strange birthmark on your forehead. Start with the cantrip spell scroll, a wand, a robe, and a strange feather that changes colors depending on your mood.", 
"Tax Collector" : "You got caught embezzling and ended up banished. Start with a rapier, a black cape, and 1d6sp in stolen taxes.", 
"Temple Guard" : "You kept watch over the entrance to a holy place of Solarion but offended the wrong priest and got sent on a pilgrimage to the frontier as punishment. Start with a mace, a religious uniform, and a holy symbol.", 
"Torchbearer" : "You’ve been in a dun- geon before, carrying a torch for an unlucky fellow who wandered into a trap. Start with a short sword and three torches.", 
"Touched by Power" : "Stumbled on a mystical place of power when you were a child and have never been the same. Start with a staff and a random spell scroll.", 
"Tracker" : "You were skilled at track- ing, able to follow footprints and other spoor through rough terrain to find your quarry. Start with a hatchet, a net, and cloak.", 
"Trapper" : "You spent years in the wild as a trapper and tanner, capturing an- imals for their furs and leathers. Start with a sling, a net, and a dagger.", 
"Troubadour" : "You were a member of a troupe of minstrels, but your fel- lows were dispatched in a bar fight. Start with a lute, a dagger, and color- ful clothing. You can sing, dance, and play the lute quite well.", 
"Urchin" : "Grew up hanging around the bustling market stalls, stealing food to survive. Start with a dagger, a bag with 1d4 bread loaves, and a small rodent creature that seems content to live in your pocket and feed off of crumbs.", 
"Vagabond" : "A drifter, never staying anywhere too long. Start with a staff, a winter cloak, and a pair of dice made from human bones.", 
"Vampire Hunter" : "Your family was enthralled and enslaved by a vam- pire. You put the demon to death but it was too late for your loved ones. Start with a necklace of garlic, a wooden stake, and a crossbow with a quiver of bolts.", 
"Veteran" : "You are a veteran of the great wars. Your body is scarred and your outlook is grim. +1 max hit points but -1 to Charisma. Start with a mace, a light shield, and a bottle of black rum.", 
"Village Hero" : "You were just a kid in a small village. Danger came knocking and you stood your ground. Common-folk naturally trust you. Start with a shortsword, a lantern, and a tendency to rush headlong toward adventure.", 
"Washed-Up Knight" : "You are a washed-up knight, down on your luck and drowning your sorrows. But you have been spurred to action by something (a mysterious voice in your head, maybe?). Gain a sword, gambeson, and a fine cloak with the emblem of a knightly order.", 
"Wolf Child" : "You were abandoned in the woods as a child and raised by a pack of wolves. -1 to Intellect and Charisma but +1 to Perception for keen sense of smell. You can’t read and don’t speak much, but you can communicate with wolves and other canines. Armor and heavy clothing makes you uncomfortable. You can safely eat raw meat without getting sick. Start with a javelin and some fur pelts.", 


}

human_backgrounds_names = ["A Pirate’s Life for Thee",
"Academician",
"Accused of Witchcraft",
"Acolyte",
"Amnesia",
"Animal Trainer",
"Ape Man",
"Apprentice Alchemist",
"Apprentice Astronomer",
"Artisan",
"Assassin in Training",
"Avenger",
"Axe-for-hire",
"Barefoot Friar",
"Blade in the Boulder",
"Bounty Hunter",
"Bowyer-Fletcher",
"Brewer",
"Brute",
"Cavalry",
"Circus Folk",
"Courtesan",
"Courtier",
"Cutpurse",
"Delusional Knight",
"Demon Cultist",
"Discovered Power",
"Dishonored",
"Escaped from a Witch",
"Escaped from Cult",
"Escaped from Prison",
"Estranged",
"Executioner",
"Exercised",
"Failed Merchant",
"Falconer",
"Far-Traveled",
"Fence",
"Fisher-folk",
"Footpad",
"Fortune Teller",
"Fugitive",
"Gambler",
"Gladiator",
"Gravedigger",
"Grievanced Farmer",
"Grifter",
"Guard at a Noble House",
"Healer",
"Hedge Mage",
"Hermit",
"Highlander",
"Hound Master",
"Ice Age Hunter",
"Imposter",
"Intrepid",
"Kidnapped Blacksmith",
"Lore Keeper",
"Mercenary",
"Merry Marksman",
"Militia Deserter",
"Miner",
"Monk",
"Moon Sage",
"Mountaineer",
"Night Watchman",
"Northern Wildling",
"Orphan",
"Outcast Heir",
"Outlaw",
"Outrider",
"Pathfinder",
"Pilgrim",
"Poison Taster",
"Questing Squire",
"Rat Catcher",
"Reborn",
"Reeve",
"Runaway Princess",
"Sailor",
"Saw the Light",
"Scullery Maid",
"Shepherd",
"Smuggler",
"Spy",
"Student Wizard",
"Tax Collector",
"Temple Guard",
"Torchbearer",
"Touched by Power",
"Tracker",
"Trapper",
"Troubadour",
"Urchin",
"Vagabond",
"Vampire Hunter",
"Veteran",
"Village Hero",
"Washed-Up Knight",
"Wolf Child"
]

human_names = [
"Adellia", 
"Adruss", 
"Alysan", 
"Annagail", 
"Armond", 
"Arren", 
"Atlia", 
"Bartog", 
"Bellynn", 
"Bim", 
"Bramun", 
"Callan", 
"Calvira", 
"Caydir", 
"Dace", 
"Divara", 
"Dreg", 
"Drusel", 
"Eckmon", 
"Elmirn", 
"Evynor", 
"Farandar", 
"Feyra", 
"Gavick", 
"Gord", 
"Haliea", 
"Hectrel", 
"Hestra", 
"Hexus", 
"Iridan", 
"Iro", 
"Isa", 
"Isadora", 
"Jasker", 
"Jormund", 
"Keldan", 
"Kienna", 
"Kromdir", 
"Kylera", 
"Leodar", 
"Ludara", 
"Lyness", 
"Maddigan", 
"Marula", 
"Maur", 
"Mordo", 
"Myrindra", 
"Narell", 
"Neeva", 
"Nelara", 
"Nevariel", 
"Nim", 
"Norick", 
"Octovia", 
"Ollara", 
"Olvir", 
"Parnan", 
"Penna", 
"Pinnia", 
"Po", 
"Quel", 
"Quillia", 
"Quillis", 
"Rebessa", 
"Rei", 
"Ren", 
"Renik", 
"Rigdar", 
"Rith", 
"Roelyn", 
"Samrund", 
"Sarabeth", 
"Sarin", 
"Sarvelia", 
"Tamlan", 
"Tillia", 
"Trellen", 
"Tukela", 
"Tylee", 
"Ulee", 
"Ulfrandir", 
"Urma", 
"Utler", 
"Valex", 
"Vendorf", 
"Veronis", 
"Vi", 
"Volgaar", 
"Vorena", 
"Wehlela", 
"Wilander", 
"Windrie", 
"Wolmir", 
"Xan", 
"Yelmina", 
"Yoren", 
"Zargus", 
"Zera", 
"Zesha", 
"Zula" 
]


human_attitude = [
"Abrasive", 
"Aggressive", 
"Agreeable", 
"Aloof", 
"Alluring", 
"Authoritative", 
"Boastful", 
"Bold", 
"Brooding", 
"Callous", 
"Cautious", 
"Cheerless", 
"Compassionate", 
"Condescending", 
"Conscientious", 
"Confident", 
"Cowardly", 
"Crude", 
"Cruel", 
"Daring", 
"Disciplined", 
"Disturbed", 
"Feisty", 
"Furtive", 
"Frantic", 
"Friendly", 
"Generous", 
"Glorious", 
"Glum", 
"Grandiose", 
"Greedy", 
"Gregarious", 
"Guarded", 
"Grumpy", 
"Harsh", 
"Haughty", 
"Helpful", 
"Honorable", 
"Hot-headed", 
"Ignorant", 
"Insightful", 
"Indifferent", 
"Imperial", 
"Inquisitive", 
"Impulsive", 
"Intrepid", 
"Judgmental", 
"Manic", 
"Manipulative", 
"Melancholy", 
"Moody", 
"Naïve", 
"Optimistic", 
"Pacifist", 
"Perfectionist", 
"Pessimistic", 
"Pious", 
"Plucky", 
"Practical", 
"Pretentious", 
"Proper", 
"Proud", 
"Pushy", 
"Rational", 
"Rebellious", 
"Reckless", 
"Relentless", 
"Resourceful", 
"Resolute", 
"Romantic", 
"Ruthless", 
"Saintly", 
"Sarcastic", 
"Secretive", 
"Selfish", 
"Selfless", 
"Sheepish", 
"Shrewd", 
"Slovenly", 
"Spiteful", 
"Stern", 
"Stoic", 
"Stubborn", 
"Surly", 
"Tactless", 
"Tenacious", 
"Thoughtful", 
"Timid", 
"Trusting", 
"Unfeeling", 
"Unpredictable", 
"Unscrupulous", 
"Unusual", 
"Valiant", 
"Vengeful", 
"Virtuous", 
"Wise", 
"Witty", 
"Worry-wort", 
"Zealous"
]

human_hair = [
"Bald", 
"Balding", 
"Braided Hair", 
"Bushy Hair", 
"Curly Hair", 
"Dirty Hair", 
"Formal Haircut", 
"Hairless", 
"Long Hair", 
"Matted Hair", 
"Mohawk", 
"Ponytail", 
"Sideburns", 
"Shaved Head", 
"Short Hair", 
"Spiky Hair", 
"Stylish Hair", 
"Tight Hair", 
"Wavy Hair", 
"Wild Hair"
]

human_face = [
"Angular", 
"Baby", 
"Blunt", 
"Chiseled", 
"Delicate", 
"Hawkish", 
"Impish", 
"Kind", 
"Long", 
"Narrow", 
"Pocked", 
"Rattish", 
"Rounded", 
"Ruddy", 
"Scarred", 
"Soft", 
"Square", 
"Sunken", 
"Wide", 
"Wolfish"
]

human_eyes = [
  "Angry", 
"Beady", 
"Bleary", 
"Bloodshot", 
"Blue", 
"Bright", 
"Bug", 
"Cross", 
"Dark", 
"Droopy", 
"Friendly", 
"Gray", 
"Green", 
"Harsh", 
"Lazy", 
"Multicolored", 
"One", 
"Piercing", 
"Shifty", 
"Sunken"
]


human_body = [
  "Arched", 
"Athletic", 
"Barrel-chested", 
"Boney", 
"Brawny", 
"Broad", 
"Built", 
"Fit", 
"Flabby", 
"Husky", 
"Lithe", 
"Odd", 
"Pudgy", 
"Rotund", 
"Scrawny", 
"Short", 
"Slender", 
"Stout", 
"Tall", 
"Wiry"
]


human_quirk = [
"Afraid of dark", 
"Always cold", 
"Always hot", 
"Always itching", 
"Animals despise", 
"Attractive", 
"Awkward", 
"Bad breath", 
"Baggy eyes", 
"Bearded", 
"Big ears", 
"Big feet", 
"Big nose", 
"Birthmark", 
"Booming voice", 
"Bowlegged", 
"Broken nose", 
"Burn scars", 
"Butterfingers", 
"Cat-like eyes", 
"Chews straw", 
"Close-talker", 
"Colorful eyes", 
"Colorful hair", 
"Crooked teeth", 
"Daydreamer", 
"Deep voice", 
"Doesn’t bathe", 
"Doesn’t laugh", 
"Drunkard", 
"Elfish ears", 
"Flaking skin", 
"Funny mustache", 
"Gnarled hands", 
"Graceful", 
"Hairy", 
"Hissing voice", 
"Hugger", 
"Hunchback", 
"Incessant sniff", 
"Jittery", 
"Juggles", 
"Just a kid", 
"Likes to bet", 
"Limp", 
"Long legs", 
"Long nails", 
"Long neck", 
"Meat-only eater", 
"Missing ear", 
"Missing eye", 
"Missing fingers", 
"Missing teeth", 
"Moles", 
"Monochrome", 
"Mouth breather", 
"Much makeup", 
"Mute", 
"Nasally voice", 
"Neat freak", 
"Old", 
"Overdressed", 
"Overly polite", 
"Pegleg", 
"Persistent cough", 
"Picks teeth", 
"Piercings", 
"Pop-eyed", 
"Pops bones", 
"Pot-bellied", 
"Quiet voice", 
"Raspy voice", 
"Rubs chin", 
"Sharp fingernails", 
"Sings", 
"Six-fingered", 
"Slob", 
"Slow-talker", 
"Smokes", 
"Snoozer", 
"Snorts", 
"Spits", 
"Sticky-fingers", 
"Stinky", 
"Stutter", 
"Superstitious", 
"Sweaty", 
"Tattoos", 
"Twiddles fingers", 
"Twitch", 
"Ugly", 
"Vegetarian", 
"Very muscular", 
"Very short", 
"Very tall", 
"Weathered skin", 
"Wierd eye", 
"Wheezy", 
"Winning smile", 
"Yawns", "Afraid of dark", 
"Always cold", 
"Always hot", 
"Always itching", 
"Animals despise", 
"Attractive", 
"Awkward", 
"Bad breath", 
"Baggy eyes", 
"Bearded", 
"Big ears", 
"Big feet", 
"Big nose", 
"Birthmark", 
"Booming voice", 
"Bowlegged", 
"Broken nose", 
"Burn scars", 
"Butterfingers", 
"Cat-like eyes", 
"Chews straw", 
"Close-talker", 
"Colorful eyes", 
"Colorful hair", 
"Crooked teeth", 
"Daydreamer", 
"Deep voice", 
"Doesn’t bathe", 
"Doesn’t laugh", 
"Drunkard", 
"Elfish ears", 
"Flaking skin", 
"Funny mustache", 
"Gnarled hands", 
"Graceful", 
"Hairy", 
"Hissing voice", 
"Hugger", 
"Hunchback", 
"Incessant sniff", 
"Jittery", 
"Juggles", 
"Just a kid", 
"Likes to bet", 
"Limp", 
"Long legs", 
"Long nails", 
"Long neck", 
"Meat-only eater", 
"Missing ear", 
"Missing eye", 
"Missing fingers", 
"Missing teeth", 
"Moles", 
"Monochrome", 
"Mouth breather", 
"Much makeup", 
"Mute", 
"Nasally voice", 
"Neat freak", 
"Old", 
"Overdressed", 
"Overly polite", 
"Pegleg", 
"Persistent cough", 
"Picks teeth", 
"Piercings", 
"Pop-eyed", 
"Pops bones", 
"Pot-bellied", 
"Quiet voice", 
"Raspy voice", 
"Rubs chin", 
"Sharp fingernails", 
"Sings", 
"Six-fingered", 
"Slob", 
"Slow-talker", 
"Smokes", 
"Snoozer", 
"Snorts", 
"Spits", 
"Sticky-fingers", 
"Stinky", 
"Stutter", 
"Superstitious", 
"Sweaty", 
"Tattoos", 
"Twiddles fingers", 
"Twitch", 
"Ugly", 
"Vegetarian", 
"Very muscular", 
"Very short", 
"Very tall", 
"Weathered skin", 
"Wierd eye", 
"Wheezy", 
"Winning smile", 
"Yawns"
]
